name: "Library Analytics App"

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

permissions:
  contents: write

env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CONFIG_DIRECTORY: "./terraform/aws/terraform-aws-library-analytics-app/"

jobs:
  terraform:
    name: "library-analytics-tf"
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: terraform/aws/terraform-aws-library-analytics-app

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.3

      - name: Terraform init
        id: init
        run: terraform init -lock=false

      - name: Terraform format
        id: fmt
        run: terraform fmt

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Apply
        # This step now triggers on pushes to main and dev branches
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false -lock=false
